confs:
  feedbackify_position: left
  feedbackify_color: '#237BAB'
advanced:
  feedbackify_visibility: 0
  feedbackify_pages: ''
_core:
  default_config_hash: CqQovpqhlXwKbc_bYDOtDI21y8QKyUQmMJidUeK2GpM
